DROP DATABASE IF EXISTS gamerental;

CREATE DATABASE gamerental;

USE gamerental;

CREATE TABLE GAMES (
GAME_ID	VARCHAR(10) PRIMARY KEY,
GAME_NAME	VARCHAR(35) NOT NULL,
STORE_ID    CHAR(2));

CREATE TABLE STORES(
STORE_ID  VARCHAR(10) PRIMARY KEY,
STORE_CITY	VARCHAR(50) NOT NULL,
STORE_COUNTRY	CHAR(2) NOT NULL);


CREATE TABLE CUSTOMER (
CUSTOMER_ID		NUMERIC(4) PRIMARY KEY,
CUSTOMER_NUMBER	VARCHAR(4)

);

CREATE TABLE RENTAL (
RENTAL_ID   	VARCHAR(50) PRIMARY KEY,
RENTAL_PRICES	VARCHAR(50) NOT NULL,
RENTAL_DATE  	VARCHAR(50) NOT NULL,
RENTAL_RETURN_DATE	VARCHAR(50) NOT NULL);

CONSTRAINT 	FK_STORE_ID FOREIGN KEY(STORE_ID) REFERENCES STORES(STORE_ID));


/* CREATING AN INDEX ON EMP_LNAME IN THE  EMPLOYEE TABLE  */

CREATE INDEX EMP_LNAME_INDEX ON EMPLOYEE(EMP_LNAME(8));


commit;


